apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        # readinessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/health
        #   periodSeconds: 3
        #   failureThreshold: 2
        #   initialDelaySeconds: 5
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/health
        #   periodSeconds: 3
        #   failureThreshold: 1
        #   initialDelaySeconds: 10
