apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec: # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    env:
    - name: MESSAGE
      value: "hello world"
    # command: ["/bin/echo", "hello", "world"]
    # Entrypoint: ["/bin/echo", "hello", "world"]
    # command: ["/bin/sh", "-c"]
    # args: ["/bin/echo \"${MESSAGE}\""]
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
