apiVersion: v1
kind: Pod
metadata:
  name: dns-observer-ndots
spec:
  containers:
  - name: dns-observer
    image: gcr.io/zihongz-k8s-dev/dns-observer-amd64:0.3-dirty
    command: ["sh", "-c"]
    args: ["while true ; do sleep 3600 ; done"]
    imagePullPolicy: Always
    volumeMounts:
      - name: resolv-conf
        mountPath: /etc/resolv.conf
        subPath: resolv.conf
  volumes:
    - name: resolv-conf
      configMap:
        name: resolvconf
        items:
        - key: resolv.conf
          path: resolv.conf
  restartPolicy: Never
