apiVersion: v1
kind: Pod
metadata:
  name: dnsmasq
spec:
  containers:
    - name: dnsmasq
      image: gcr.io/google_containers/kube-dnsmasq-amd64:1.3
      args:
      - --cache-size=1000
      - --no-resolv
      - --server=127.0.0.1#10053
      - --log-facility=-
      ports:
      - containerPort: 53
        name: dns
        protocol: UDP
      - containerPort: 53
        name: dns-tcp
        protocol: TCP
