apiVersion: v1
kind: Pod
metadata:
  name: dns-observer
spec:
  containers:
  - name: dns-observer
    image: gcr.io/zihongz-k8s-dev/dns-observer-amd64:0.3-dirty
    command: ["sh", "-c"]
    args: ["while true ; do sleep 3600 ; done"]
    imagePullPolicy: Always
  restartPolicy: Never
