apiVersion: v1
kind: Pod
metadata:
  name: busybox
  # namespace: kube-system
spec:
  containers:
  - name: wget-test
    image: gcr.io/google_containers/busybox:1.24
    command: ["sh", "-c"]
    args: ["while true ; do sleep 3600 ; done"]
    # args: ["wget --timeout=30 google.com"]
  restartPolicy: Never
