apiVersion: v1
kind: Pod
metadata:
  name: healthz
spec:
  containers:
  - name: healthz
    image: gcr.io/google_containers/exechealthz-amd64:1.1
    command: ["/bin/sh","-c"]
    args: ["/exechealthz -cmd='ls /etc' -port=8080 -quiet & /exechealthz -cmd='ls /etc' -port=8082 -quiet"]
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8082
      protocol: TCP
