apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  labels:
    test: "true"
spec:
  replicas: 1
  selector:
    run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
