apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v19
  labels:
    k8s-app: kube-dns
    version: v19
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v19
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v19
    spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/busybox:1.24
        command: ["/bin/sh", "-c"]
        args: ["sleep 3600"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      - name: dnsmasq
        image: gcr.io/google_containers/busybox:1.24
        command: ["/bin/sh", "-c"]
        args: ["sleep 3600"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz-amd64:1.1
        command: ["/bin/sh","-c"]
        args: ["/exechealthz -cmd='ls >/dev/null' -port=8082 -quiet & /exechealthz -cmd='ls >/dev/null' -port=8080 -quiet"]
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8082
          protocol: TCP
      dnsPolicy: Default  # Don't use cluster DNS.
