apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  loadBalancerSourceRanges: ["0.0.0.0/1", "128.0.0.0/1"]
  selector:
    run: my-nginx
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
