apiVersion: v1
kind: Service
metadata:
  name: netexec
  labels:
    run: netexec
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    run: netexec
  ports:
  - port: 29999
    protocol: TCP
  type: LoadBalancer
