apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-1
  labels:
    run: my-nginx
    test: "true"
spec:
  # replicas: 2
  selector:
    run: my-nginx
  template:
    metadata:
      labels:
          run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
